### ISSUE TITLE
apk created w/buildozer crashes in case of multiple python source file

### ISSUE THREAD

**Issue by tanayz** [ohaz/buildozer-gui#1]
I've run buildozer successfully to deploy apk file that has been made with single python file say main.py.
However whenever I'm using additional python file and calling that from main.py,the program runs fine in my desktop even installs successfully in android device,but crashes when launched in android.Do you have any suggestion for that,something like whether it's the norm for buildozer to have a single python file.

**Comment by ohaz** [comment]
It's definitely not normal for buildozer to just allow a single file. It usually works fine with larger problems. Do you get any error messages?

PS: This is usually not the spot to ask for buildozer related questions, just buildozer-gui related problems/questions. Please use the issue tracker or the help system for kivy/buildozer in future!
